package hosiptal;

import java.net.ConnectException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class NewJFrame1 extends javax.swing.JFrame {
        Connection con2;
         Connection con1;
  ArrayList<Integer> ids=new ArrayList<>();
        DefaultTableModel dtm;
         ArrayList<Integer> empids=new ArrayList<>();
    /**
     * Creates new form NewJFrame1
     */
    public NewJFrame1() {
        initComponents();
        dtm=new DefaultTableModel();
          dtm.addColumn("Name");
    dtm.addColumn("Specialization");
    dtm.addColumn("Gender");
    dtm.addColumn("Address");
    dtm.addColumn("phone Number");
        this.setLocationRelativeTo(null);
        try {
          con2=DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital_2", "root", "amr01069791974");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Connection FAILED");
        }
            try {
                con1=DriverManager.getConnection("jdbc:mysql://localhost:3306/hosiptal", "root", "amr01069791974");
            } catch (SQLException ex) {
                Logger.getLogger(NewJFrame1.class.getName()).log(Level.SEVERE, null, ex);
            }
        
            filltable();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        special = new javax.swing.JTextField();
        docName = new javax.swing.JTextField();
        phoenumber = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        nameofpatient = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        btn_save2 = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        btn_save1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jLabel1.setText("     Doctor Inforamtion");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 29, 790, 44));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Doctor Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 92, 118, 28));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("speilaization");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 146, 118, 28));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Doctor`s Patients");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 199, 118, 28));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Gender");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 146, 118, 28));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Phone Num");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 199, 118, 28));
        jPanel1.add(special, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 146, 208, 28));
        jPanel1.add(docName, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 92, 208, 28));

        phoenumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoenumberActionPerformed(evt);
            }
        });
        jPanel1.add(phoenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 202, 208, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Address");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 91, 84, 28));
        jPanel1.add(nameofpatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 202, 208, -1));
        jPanel1.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 95, 226, -1));

        buttonGroup1.add(male);
        male.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        male.setSelected(true);
        male.setText("Male");
        jPanel1.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 147, 98, -1));

        buttonGroup1.add(female);
        female.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        female.setText("Female");
        jPanel1.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 147, 98, -1));

        jButton1.setText("←");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btn_save2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_save2.setText("SAVE");
        btn_save2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_save2save_function(evt);
            }
        });
        jPanel1.add(btn_save2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, 116, 30));

        btn_save.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_save.setText("Update");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatefun(evt);
            }
        });
        jPanel1.add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 116, 30));

        btn_save1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_save1.setText("Delete");
        btn_save1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletefun(evt);
            }
        });
        jPanel1.add(btn_save1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 116, 30));

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table2);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, 190));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hosiptal/photo/back.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 790, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private void filltable(){
     try {
         
     dtm.setRowCount(0);
            PreparedStatement stm=con2.prepareStatement("select doc_id,doc_name,specialization,gender,address,phone_number from doctor" );
           ResultSet rs= stm.executeQuery();
           while(rs.next()){
                  empids.add(rs.getInt(1));
         dtm.addRow(new Object[]{rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6)});
           
           }
           table2.setModel(dtm);
        } catch (SQLException ex) {
           // Logger.getLogger(patient.class.getName()).log(Level.SEVERE, null, ex);
           JOptionPane.showMessageDialog(this, "ERROR");
        }
    
 
    
    }
     
     
     
     
     
    private void updatefun(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatefun
        // TODO add your handling code here:
        if(
                !docName.getText().isEmpty()&&!special.getText().isEmpty()&&!phoenumber.getText().isEmpty()){
        try {
            // TODO add your handling code here:
           //dtm.setRowCount(0); 
            PreparedStatement stm=con2.prepareStatement("update doctor  set doc_name=?,specialization=?,gender=?,address=?,phone_number=? where doc_id=? ");
            stm.setString(1, docName.getText());
            if(male.isSelected())
                stm.setString(3, "male");
            else
                stm.setString(3, "female");
            stm.setString(2, special.getText());
            stm.setString(4, address.getText());
            stm.setString(5, phoenumber.getText());
            stm.setInt(6, empids.get(table2.getSelectedRow()));
            stm.executeUpdate();
            JOptionPane.showMessageDialog(this, "Updated successfully");
            filltable();
            docName.setText(null);
            special.setText(null);
          
            phoenumber.setText(null);
            address.setText(null);
        } catch (SQLException ex) {
            Logger.getLogger(patient.class.getName()).log(Level.SEVERE, null, ex);
        }}
        else
            JOptionPane.showMessageDialog(this,"Not Saved");        
        
       
    }//GEN-LAST:event_updatefun

    
    private void deletefun(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletefun
        // TODO add your handling code here:
            try {
            // TODO add your handling code here:
            PreparedStatement stm=con2.prepareStatement("delete from doctor where doc_id=? ");
            
            stm.setInt(1, empids.get(table2.getSelectedRow()));
            stm.executeUpdate();
            JOptionPane.showMessageDialog(this, "Deleted successfully");
            filltable();
            docName.setText(null);
            special.setText(null);
          
            phoenumber.setText(null);
            address.setText(null);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error");
        }
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_deletefun

    private void btn_save2save_function(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_save2save_function
        // TODO add your handling code here:
         if(
                !docName.getText().isEmpty()&&!special.getText().isEmpty()&&!phoenumber.getText().isEmpty()){
        try {
            // TODO add your handling code here:
            PreparedStatement stm=con2.prepareStatement("insert into doctor(doc_name,specialization,gender,address,phone_number)values(?,?,?,?,? )");
            stm.setString(1, docName.getText());
            if(male.isSelected())
                stm.setString(3, "male");
            else
                stm.setString(3, "female");
            stm.setString(2, special.getText());
            stm.setString(4, address.getText());
            stm.setString(5, phoenumber.getText());
            stm.executeUpdate();
            JOptionPane.showMessageDialog(this, "Added successfully");
            filltable();
             docName.setText(null);
            special.setText(null);
          
            phoenumber.setText(null);
            address.setText(null);
        } catch (SQLException ex) {
            Logger.getLogger(patient.class.getName()).log(Level.SEVERE, null, ex);
        }}
        else
            JOptionPane.showMessageDialog(this,"Not Saved");
    }//GEN-LAST:event_btn_save2save_function

    private void table2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table2MouseClicked
        // TODO add your handling code here:
         docName.setText(table2.getValueAt(table2.getSelectedRow(), 0).toString());
        
        special.setText(table2.getValueAt(table2.getSelectedRow(),1).toString());
        if(table2.getValueAt(table2.getSelectedRow(), 2).toString().equals("female"))
        female.setSelected(true);
        else
        male.setSelected(true);
        address.setText(table2.getValueAt(table2.getSelectedRow(), 3).toString());
        phoenumber.setText(table2.getValueAt(table2.getSelectedRow(), 4).toString());
    }//GEN-LAST:event_table2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new choosepage().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void phoenumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoenumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoenumberActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_save1;
    private javax.swing.JButton btn_save2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField docName;
    private javax.swing.JRadioButton female;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField nameofpatient;
    private javax.swing.JTextField phoenumber;
    private javax.swing.JTextField special;
    private javax.swing.JTable table2;
    // End of variables declaration//GEN-END:variables
}
